Kommentar:)
mariuf17/nordicdoor pull request #417
Opened 2022-11-11 12:09 UTC by ThomasTvedten

2022-11-11 13:11 UTC, mariuf17 requested changes
Endre kommentar til "Spørring som viser ansatte som har deaktiverte brukerkontoer"

2022-11-15 11:12 UTC, Trulsd approved these changes

2022-11-16 09:57 UTC, StianSteinsland approved these changes

2022-11-16 09:57 UTC, StianSteinsland approved these changes

2022-11-16 09:59 UTC, sindre-kristiansen approved these changes

2022-11-16 09:59 UTC, merged